// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejhxxmwrnxsjxacdeaqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaHh4bXdybnhzanhhY2RlYXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDU5NjgsImV4cCI6MjA3MTA4MTk2OH0.PAYSOQRAfkMilWRjiBUB7zLnyBGCb_AzQHMPwpmBp2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});